CREATE PROCEDURE [dbo].[USP_CHECK_DUPLICATE_TEMPLATE]
	@TEMPLATE VARCHAR(500)
AS
	BEGIN
	IF((SELECT COUNT(*) FROM DocumentPreparation_PSY WHERE template_PSY=@TEMPLATE) > 1)
	BEGIN
	SELECT 1
	END
	ELSE
	SELECT 0
	END
