CREATE PROCEDURE [dbo].[USP_GetTemplateHeaderFooterDetails]
@TemplateName varchar(500),@PrepId int=0
as
begin

DECLARE @REVIEWERS TABLE(TEMPLATE_NAME VARCHAR(500), USERNAME VARCHAR(500),DEPTNAME VARCHAR(500),ROLENAME VARCHAR(500),REVIEWDATE DATETIME)
DECLARE @APPROVERS TABLE(TEMPLATE_NAME VARCHAR(500), USERNAME VARCHAR(500),DEPTNAME VARCHAR(500),ROLENAME VARCHAR(500),APPROVEDATE DATETIME)
DECLARE @PREPAREDBY TABLE(TEMPLATE_NAME VARCHAR(500), USERNAME VARCHAR(500),DEPTNAME VARCHAR(500),ROLENAME VARCHAR(500),PREPAREDDATE DATETIME)
DECLARE @GUIDS TABLE(ID UNIQUEIDENTIFIER)

DECLARE @WORKFLOWS TABLE(WORKFLOWNAME VARCHAR(500))
INSERT @WORKFLOWS
SELECT WORKFLOW_PSY FROM Documentrequest_PSY DR
JOIN DocumentPreparation_PSY DP ON DP.Refrence_PSY=DR.DRID_PSY WHERE DP.template_PSY=@TEMPLATENAME AND DP.DPNID_PSY=@PrepId
INSERT @WORKFLOWS
SELECT WOKFLOW_PSY FROM DocumentPreparation_PSY WHERE template_PSY=@TEMPLATENAME AND DPNID_PSY=@PrepId AND wokflow_PSY NOT IN (SELECT WORKFLOWNAME FROM @WORKFLOWS)
INSERT @WORKFLOWS
SELECT Workflow_PSY FROM DocumentEffective_PSY DE
JOIN DocumentPreparation_PSY DP ON DP.Documentmanagerid_PSY=DP.DPNID_PSY WHERE DP.template_PSY=@TEMPLATENAME AND DP.DPNID_PSY=@PrepId
AND DE.Workflow_PSY NOT IN (SELECT WORKFLOWNAME FROM @WORKFLOWS)

INSERT @GUIDS
SELECT TOP(1) GUID_DR FROM Documentrequest_PSY DR
JOIN DocumentPreparation_PSY DP ON DP.Refrence_PSY=DR.DRID_PSY WHERE DP.template_PSY=@TEMPLATENAME AND DP.DPNID_PSY=@PrepId
INSERT @GUIDS
SELECT TOP(1) GUID_DP FROM DocumentPreparation_PSY WHERE template_PSY=@TEMPLATENAME AND DPNID_PSY=@PrepId
INSERT @GUIDS
SELECT TOP(1) DE.GUID_DE FROM DocumentEffective_PSY DE
JOIN DocumentPreparation_PSY DP ON DP.Documentmanagerid_PSY=DP.DPNID_PSY WHERE DP.template_PSY=@TEMPLATENAME AND DP.DPNID_PSY=@PrepId


INSERT @REVIEWERS
SELECT DISTINCT @TEMPLATENAME,USR.UserID_PSY,USR.Department_PSY,USR.Role_PSY,WI.ModifiedDate_PSY 
FROM workitems_PSY WI 
JOIN @GUIDS G ON G.ID=WI.RefrenceGuid_PSY
JOIN UserConfiguration_PSY USR ON USR.UserID_PSY=WI.CreatedBy_PSY
WHERE  WI.ActionType_PSY='REVIEW' AND WI.IsCompleted_PSY=1

INSERT @APPROVERS
SELECT DISTINCT @TEMPLATENAME,USR.UserID_PSY,USR.Department_PSY,USR.Role_PSY,WI.ModifiedDate_PSY 
FROM workitems_PSY WI 
JOIN @GUIDS G ON G.ID=WI.RefrenceGuid_PSY
JOIN UserConfiguration_PSY USR ON USR.UserID_PSY=WI.CreatedBy_PSY
WHERE  WI.ActionType_PSY='APPROVE' AND WI.IsCompleted_PSY=1

INSERT @PREPAREDBY
SELECT DP.template_PSY ,DR.CreatedBy_PSY,USR.Department_PSY,USR.Role_PSY,DR.ModifiedDate_PSY FROM Documentrequest_PSY DR
LEFT JOIN DocumentPreparation_PSY DP ON DP.ReferenceGuid_PSY=DR.GUID_DR
LEFT JOIN UserConfiguration_PSY USR ON USR.UserID_PSY=DR.CreatedBy_PSY
WHERE DP.template_PSY=@TemplateName AND DP.DPNID_PSY=@PrepId

INSERT @PREPAREDBY
SELECT DP.template_PSY ,DP.CreatedBy_PSY,USR.Department_PSY,USR.Role_PSY,DP.ModifiedDate_PSY FROM DocumentPreparation_PSY DP
LEFT JOIN UserConfiguration_PSY USR ON USR.UserID_PSY=DP.CreatedBy_PSY
WHERE DP.template_PSY=@TemplateName AND DP.DPNID_PSY=@PrepId

INSERT @PREPAREDBY
SELECT DP.template_PSY ,DE.CreatedBy_PSY,USR.Department_PSY,USR.Role_PSY,DE.ModifiedDate_PSY FROM DocumentEffective_PSY DE
LEFT JOIN DocumentPreparation_PSY DP ON DP.GUID_DP=DE.ReferenceGuid_PSY
LEFT JOIN UserConfiguration_PSY USR ON USR.UserID_PSY=DE.CreatedBy_PSY
WHERE DP.template_PSY=@TemplateName AND DP.DPNID_PSY=@PrepId


SELECT TOP(1) DP.documenttitle_PSY,DP.documentno_PSY,DP.department_PSY,AT.Version,(VERSION-1) AS Supersedes,
DE.EffectiveDate_PSY,DE.Reviewdate_PSY,DP.department_PSY,DP.GUID_DP,DE.GUID_DE,
(SELECT STRING_AGG(USERNAME,',') FROM @REVIEWERS) AS REVIWED_BY,
(SELECT STRING_AGG(USERNAME,',') FROM @APPROVERS) AS APPROVED_BY,
(SELECT STRING_AGG(FORMAT(REVIEWDATE,'dd/MM/yyyy'),',') FROM @REVIEWERS) AS REVIEWDATES,
STRING_AGG(PR.UserName, ',') AS PREPARED_BY,
(SELECT STRING_AGG(DEPTNAME,',') FROM @APPROVERS) AS APPROVEDDEPT,
(SELECT STRING_AGG(DEPTNAME,',') FROM @REVIEWERS) AS REVIWEDDEPT,
(SELECT STRING_AGG(FORMAT(APPROVEDATE,'dd/MM/yyyy'),',') FROM @APPROVERS) AS APPROVEDATES,
STRING_AGG(PR.DEPTNAME, ',') AS PREPAREDDEPT,
(SELECT STRING_AGG(ROLENAME,',') FROM @APPROVERS) AS APPROVEDROLE,
(SELECT STRING_AGG(ROLENAME,',') FROM @REVIEWERS) AS REVIWEDROLE,
(SELECT STRING_AGG(FORMAT(PREPAREDDATE,'dd/MM/yyyy'),',') FROM @PREPAREDBY) AS PREPAREDDATES,
STRING_AGG(PR.ROLENAME, ',') AS PREPAREDROLE,
DP.CreatedDate_PSY AS PREAPREDDATE,DPP.PrintCopy_PSY,DPP.reason_PSY,DP.DPNID_PSY,DPP.BatchNumber,DPP.BatchSize
FROM DocumentPreparation_PSY DP 
LEFT JOIN DocumentEffective_PSY DE ON DE.ReferenceGuid_PSY=DP.GUID_DP
LEFT JOIN AdditionalTask_PSY AT ON AT.ReferenceGuid_PSY=DE.GUID_DE
LEFT JOIN DocumentPrint_PSY DPP ON DPP.ReferenceGuid_PSY=DP.GUID_DP AND DPP.IsActive_PSY=1
JOIN @PREPAREDBY PR ON PR.TEMPLATE_NAME=DP.template_PSY
WHERE DP.template_PSY=@TemplateName AND DP.DPNID_PSY=@PrepId
GROUP BY
    DP.documenttitle_PSY,
    DP.documentno_PSY,
    AT.Version,
    DP.department_PSY,
    DE.EffectiveDate_PSY,
    DE.Reviewdate_PSY,
    DP.CreatedDate_PSY,
    DP.department_PSY,
    DPP.PrintCopy_PSY,
    DPP.reason_PSY,DP.GUID_DP,DE.GUID_DE,DP.DPNID_PSY,DPP.BatchNumber,DPP.BatchSize


end