//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    
    
    using Vlims.Services;
    using Vlims.Entities.Common;
    using Vlims.Entities;


    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/documentrevision")]
    public class DocumentRevisionController : ControllerBase
    {
        
        private readonly IDocumentRevisionService documentRevisionService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="documentRevisionService"></param>
        public DocumentRevisionController(IDocumentRevisionService documentRevisionService)
        {
            this.documentRevisionService = documentRevisionService;
        }
        
        /// <summary>
        /// This method is used to Get List of DocumentRevision
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost()]
        public ActionResult<ResponseContext<DocumentRevision>> GetAllDocumentRevision(RequestContext requestContext)
        {
            var result = documentRevisionService.GetAllDocumentRevision(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get DocumentRevision By Id dRId
        /// </summary>
        /// <param name="dRId"></param>
        [HttpGet("{dRId}")]
        public ActionResult<DocumentRevision> GetDocumentRevisionByDRId(string dRId)
        {
            var result = documentRevisionService.GetDocumentRevisionByDRId(dRId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save DocumentRevision
        /// </summary>
        /// <param name="documentRevision"></param>
        [HttpPost("savedocumentrevision")]
        public ActionResult<System.Boolean> SaveDocumentRevision(DocumentRevision documentRevision)
        {
            var result = documentRevisionService.SaveDocumentRevision(documentRevision);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update DocumentRevision
        /// </summary>
        /// <param name="documentRevision"></param>
        [HttpPost("updatedocumentrevision")]
        public ActionResult<System.Boolean> UpdateDocumentRevision(DocumentRevision documentRevision)
        {
            var result = documentRevisionService.UpdateDocumentRevision(documentRevision);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete DocumentRevision By Id dRId
        /// </summary>
        /// <param name="dRId"></param>
        [HttpDelete("{dRId}")]
        public ActionResult<bool> DeleteDocumentRevisionByDRId(string dRId)
        {
            var result = documentRevisionService.DeleteDocumentRevisionByDRId(dRId);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete DocumentRevision By Multiple ids dRIds
        /// </summary>
        /// <param name="dRIds"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllDocumentRevision(List<int> dRIds)
        {
            var result = documentRevisionService.DeleteAllDocumentRevision(dRIds);
            return result;
        }
    }
}
