//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using PolicySummary.Common.Entities;
    using PolicySummary.Sheet1.Entities;
    using PolicySummary.Sheet1.Services;
    
    
    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/documentmaster")]
    public class DocumentMasterController : ControllerBase
    {
        
        private readonly IDocumentMasterService documentMasterService;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="documentMasterService"></param>
        public DocumentMasterController(IDocumentMasterService documentMasterService)
        {
            this.documentMasterService = documentMasterService;
        }
        
        /// <summary>
        /// This method is used to Get List of DocumentMaster
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost()]
        public ActionResult<ResponseContext<DocumentMaster>> GetAllDocumentMaster(RequestContext requestContext)
        {
            var result = documentMasterService.GetAllDocumentMaster(requestContext);
            return result;
        }
        
        /// <summary>
        /// This method is used to Get DocumentMaster By Id dmid
        /// </summary>
        /// <param name="dmid"></param>
        [HttpGet("{dmid}")]
        public ActionResult<DocumentMaster> GetDocumentMasterByDmid(int dmid)
        {
            var result = documentMasterService.GetDocumentMasterByDmid(dmid);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Save DocumentMaster
        /// </summary>
        /// <param name="documentMaster"></param>
        [HttpPost("savedocumentmaster")]
        public ActionResult<System.Boolean> SaveDocumentMaster(DocumentMaster documentMaster)
        {
            var result = documentMasterService.SaveDocumentMaster(documentMaster);
            return result;
        }
        
        /// <summary>
        /// This Method is used to update DocumentMaster
        /// </summary>
        /// <param name="documentMaster"></param>
        [HttpPost("updatedocumentmaster")]
        public ActionResult<System.Boolean> UpdateDocumentMaster(DocumentMaster documentMaster)
        {
            var result = documentMasterService.UpdateDocumentMaster(documentMaster);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete DocumentMaster By Id dmid
        /// </summary>
        /// <param name="dmid"></param>
        [HttpDelete("{dmid}")]
        public ActionResult<bool> DeleteDocumentMasterByDmid(int dmid)
        {
            var result = documentMasterService.DeleteDocumentMasterByDmid(dmid);
            return result;
        }
        
        /// <summary>
        /// This Method is used to Delete DocumentMaster By Multiple ids dmids
        /// </summary>
        /// <param name="dmids"></param>
        [HttpDelete("deleteAll")]
        public ActionResult<bool> DeleteAllDocumentMaster(List<int> dmids)
        {
            var result = documentMasterService.DeleteAllDocumentMaster(dmids);
            return result;
        }
    }
}
