//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentManager.DataAccess
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Vlims.DMS.Entities;
    using Vlims.Common;

    // using VAMLIbrary.Core.Validators;


    // Comment
    public static class DocumentrequestValidator
    {

        public static string IsValidDocumentrequest(Documentrequest documentrequest)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(documentrequest.DRID, nameof(documentrequest.DRID)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.DRID, 150, nameof(documentrequest.DRID)));
                validationMessages.Append(validationHelper.NullCheckValidator(documentrequest.documentmanagerid, nameof(documentrequest.documentmanagerid)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.documentmanagerid, 150, nameof(documentrequest.documentmanagerid)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.documenttype, 150, nameof(documentrequest.documenttype)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.department, 500, nameof(documentrequest.department)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.Purpose, 500, nameof(documentrequest.Purpose)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.AssigntoGroup, 500, nameof(documentrequest.AssigntoGroup)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.CreatedBy, 150, nameof(documentrequest.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentrequest.ModifiedBy, 150, nameof(documentrequest.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','), 1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
