//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using PolicySummary.Common.Entities;
    using PolicySummary.Sheet1.Entities;
    
    
    // Comment
    public interface IworkflowconigurationService
    {
        
        ResponseContext<workflowconiguration> GetAllworkflowconiguration(RequestContext requestContext);
        
        workflowconiguration GetworkflowconigurationByWFCId(int wFCId);
        
        bool Saveworkflowconiguration(workflowconiguration workflowconiguration);
        
        bool Updateworkflowconiguration(workflowconiguration workflowconiguration);
        
        bool DeleteworkflowconigurationByWFCId(int wFCId);
        
        bool DeleteAllworkflowconiguration(List<int> wFCIds);
    }
}
