//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using PolicySummary.Sheet1.Entities;
    using VAMLIbrary.Core.Extentions;
    using PolicySummary.Common.Entities;
    
    
    // Comment
    public static class DocumentMasterConverter
    {
        
        public static List<DocumentMaster> SetAllDocumentMaster(DataSet dataset)
        {
            try
            {
                List<DocumentMaster> result = new List<DocumentMaster>();
                DocumentMaster documentMasterData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        documentMasterData = new DocumentMaster();
                        documentMasterData.Dmid = Convert.ToString(row[DocumentMasterConstants.Dmid.TrimAt()]);
                        documentMasterData.Documentypeconfiguration = Convert.ToString(row[DocumentMasterConstants.Documentypeconfiguration.TrimAt()]);
                        documentMasterData.Documentemplateonfiguration = Convert.ToString(row[DocumentMasterConstants.Documentemplateonfiguration.TrimAt()]);
                        documentMasterData.WorkFlowConfiguration = Convert.ToString(row[DocumentMasterConstants.WorkFlowConfiguration.TrimAt()]);
                        documentMasterData.NotificationConfiguration = Convert.ToString(row[DocumentMasterConstants.NotificationConfiguration.TrimAt()]);
                        documentMasterData.DashboardConfiguration = Convert.ToString(row[DocumentMasterConstants.DashboardConfiguration.TrimAt()]);
                        documentMasterData.CreatedBy = Convert.ToString(row[DocumentMasterConstants.CreatedBy.TrimAt()]);
                        documentMasterData.CreatedDate = DatatypeConverter.SetDateTime(row[DocumentMasterConstants.CreatedDate.TrimAt()]);
                        documentMasterData.ModifiedBy = Convert.ToString(row[DocumentMasterConstants.ModifiedBy.TrimAt()]);
                        documentMasterData.ModifiedDate = DatatypeConverter.SetDateTime(row[DocumentMasterConstants.ModifiedDate.TrimAt()]);
                        result.Add(documentMasterData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static DocumentMaster SetDocumentMaster(DataSet dataset)
        {
            var result = SetAllDocumentMaster(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
