//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Vlims.Entities.Common;
    using Vlims.Entities;




    // Comment
    public interface IDocumentMasterService
    {
        
        ResponseContext<DocumentMaster> GetAllDocumentMaster(RequestContext requestContext);
        
        DocumentMaster GetDocumentMasterByDmid(int dmid);
        
        bool SaveDocumentMaster(DocumentMaster documentMaster);
        
        bool UpdateDocumentMaster(DocumentMaster documentMaster);
        
        bool DeleteDocumentMasterByDmid(int dmid);
        
        bool DeleteAllDocumentMaster(List<int> dmids);
    }
}
