//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    
    
    
    
    // Comment
    public interface IAdditionalTaskService
    {
        
        ResponseContext<AdditionalTask> GetAllAdditionalTask(RequestContext requestContext);
        
        AdditionalTask GetAdditionalTaskByATID(string aTID);
        
        bool SaveAdditionalTask(AdditionalTask additionalTask);
        
        bool UpdateAdditionalTask(AdditionalTask additionalTask);
        
        bool DeleteAdditionalTaskByATID(string aTID);
        
        bool DeleteAllAdditionalTask(List<int> aTIDs);
    }
}
