//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Services
{
    using System;
    using System.Text;
    using System.Linq;
    using Vlims.Common;
    using Vlims.DocumentMaster.Entities;

    // Comment
    public static class DocumentTypeConfigurationValidator
    {

        public static string IsValidDocumentTypeConfiguration(DocumentTypeConfiguration documentTypeConfiguration)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(documentTypeConfiguration.DTCId, nameof(documentTypeConfiguration.DTCId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.DTCId, 150, nameof(documentTypeConfiguration.DTCId)));
                validationMessages.Append(validationHelper.NullCheckValidator(documentTypeConfiguration.DocumentMasterId, nameof(documentTypeConfiguration.DocumentMasterId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.DocumentMasterId, 150, nameof(documentTypeConfiguration.DocumentMasterId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.Documenttypename, 150, nameof(documentTypeConfiguration.Documenttypename)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.documenttypeprefix, 150, nameof(documentTypeConfiguration.documenttypeprefix)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.Description, 500, nameof(documentTypeConfiguration.Description)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.Assigntodepartment, 150, nameof(documentTypeConfiguration.Assigntodepartment)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.CreatedBy, 150, nameof(documentTypeConfiguration.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(documentTypeConfiguration.ModifiedBy, 150, nameof(documentTypeConfiguration.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','), 1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
