//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Vlims.Administration.Manager;
    
    using Vlims.Administration.Entities;
    using Vlims.Common;


    /// <summary>
    /// Comment
    /// </summary>
    [ApiController()]
    [Route("api/auditconfiguration")]
    public class AuditConfigurationController : ControllerBase
    {

        private readonly IAuditConfigurationService auditConfigurationService;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="roleConfigurationService"></param>
        public AuditConfigurationController(IAuditConfigurationService auditConfigService)
        {
            this.auditConfigurationService = auditConfigService;
        }

        /// <summary>
        /// This method is used to Get List of RoleConfiguration
        /// </summary>
        /// <param name="requestContext"></param>
        [HttpPost("getaudit")]
        public ActionResult GetAllAuditConfiguration(string type)
        {
            var result = auditConfigurationService.GetAllAuditConfiguration(type);
            return Ok(result);
        }
        
       
        /// <summary>
        /// This Method is used to Save RoleConfiguration
        /// </summary>
        /// <param name="roleConfiguration"></param>
        [HttpPost("saveauditconfiguration")]
        public ActionResult<System.Boolean> SaveAuditConfiguration(AuditLogEntity auditConfiguration)
        {
            var result = auditConfigurationService.SaveAuditConfiguration(auditConfiguration);
            return result;
        }
      
    }
}
