//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using PolicySummary.Sheet1.Entities;
    using VAMLIbrary.Core.Extentions;
    using PolicySummary.Common.Entities;
    
    
    // Comment
    public static class RoleConfigurationConverter
    {
        
        public static List<RoleConfiguration> SetAllRoleConfiguration(DataSet dataset)
        {
            try
            {
                List<RoleConfiguration> result = new List<RoleConfiguration>();
                RoleConfiguration roleConfigurationData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        roleConfigurationData = new RoleConfiguration();
                        roleConfigurationData.ROCFId = Convert.ToString(row[RoleConfigurationConstants.ROCFId.TrimAt()]);
                        roleConfigurationData.HierarchyManagementId = Convert.ToString(row[RoleConfigurationConstants.HierarchyManagementId.TrimAt()]);
                        roleConfigurationData.Role = Convert.ToString(row[RoleConfigurationConstants.Role.TrimAt()]);
                        roleConfigurationData.Department = Convert.ToString(row[RoleConfigurationConstants.Department.TrimAt()]);
                        roleConfigurationData.Comments = Convert.ToString(row[RoleConfigurationConstants.Comments.TrimAt()]);
                        roleConfigurationData.CreatedBy = Convert.ToString(row[RoleConfigurationConstants.CreatedBy.TrimAt()]);
                        roleConfigurationData.CreatedDate = DatatypeConverter.SetDateTime(row[RoleConfigurationConstants.CreatedDate.TrimAt()]);
                        roleConfigurationData.ModifiedBy = Convert.ToString(row[RoleConfigurationConstants.ModifiedBy.TrimAt()]);
                        roleConfigurationData.ModifiedDate = DatatypeConverter.SetDateTime(row[RoleConfigurationConstants.ModifiedDate.TrimAt()]);
                        result.Add(roleConfigurationData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static RoleConfiguration SetRoleConfiguration(DataSet dataset)
        {
            var result = SetAllRoleConfiguration(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
        
        public static DataTable SetDataSet(List<RoleConfiguration> roleConfigurations)
        {
            DataTable dataTable = new DataTable();
            DataRow row = null;
            SetDataTableColumns(dataTable);
            try
            {
                if (roleConfigurations != null && roleConfigurations.Count > 0)
                {
                    for (int i = 0; (i < roleConfigurations.Count); i = (i + 1))
                    {
                        row = dataTable.NewRow();
                        row[RoleConfigurationConstants.ROCFId.TrimAt()] = roleConfigurations[i].ROCFId;
                        row[RoleConfigurationConstants.HierarchyManagementId.TrimAt()] = roleConfigurations[i].HierarchyManagementId;
                        row[RoleConfigurationConstants.Role.TrimAt()] = roleConfigurations[i].Role;
                        row[RoleConfigurationConstants.Department.TrimAt()] = roleConfigurations[i].Department;
                        row[RoleConfigurationConstants.Comments.TrimAt()] = roleConfigurations[i].Comments;
                        row[RoleConfigurationConstants.CreatedBy.TrimAt()] = roleConfigurations[i].CreatedBy;
                        row[RoleConfigurationConstants.CreatedDate.TrimAt()] = roleConfigurations[i].CreatedDate;
                        row[RoleConfigurationConstants.ModifiedBy.TrimAt()] = roleConfigurations[i].ModifiedBy;
                        row[RoleConfigurationConstants.ModifiedDate.TrimAt()] = roleConfigurations[i].ModifiedDate;
                        dataTable.Rows.Add(row);
                    }
                }
                return dataTable;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        private static void SetDataTableColumns(DataTable dataTable)
        {
            dataTable.TableName = "UT_RoleConfiguration_PSY";
            dataTable.Columns.Add(RoleConfigurationConstants.ROCFId.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.HierarchyManagementId.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.Role.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.Department.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.Comments.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.CreatedBy.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.CreatedDate.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.ModifiedBy.TrimAt());
            dataTable.Columns.Add(RoleConfigurationConstants.ModifiedDate.TrimAt());
        }
    }
}
