//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    
    
    
    
    // Comment
    public interface IdashboardconfigurationService
    {
        
        ResponseContext<dashboardconfiguration> GetAlldashboardconfiguration(RequestContext requestContext);
        
        dashboardconfiguration GetdashboardconfigurationByDCId(int dCId);
        
        bool Savedashboardconfiguration(dashboardconfiguration dashboardconfiguration);
        
        bool Updatedashboardconfiguration(dashboardconfiguration dashboardconfiguration);
        
        bool DeletedashboardconfigurationByDCId(int dCId);
        
        bool DeleteAlldashboardconfiguration(List<int> dCIds);
    }
}
