//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using PolicySummary.Sheet1.Entities;
    using VAMLIbrary.Core.Extentions;
    using PolicySummary.Common.Entities;
    
    
    // Comment
    public static class DocumentRevisionConverter
    {
        
        public static List<DocumentRevision> SetAllDocumentRevision(DataSet dataset)
        {
            try
            {
                List<DocumentRevision> result = new List<DocumentRevision>();
                DocumentRevision documentRevisionData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        documentRevisionData = new DocumentRevision();
                        documentRevisionData.DRId = Convert.ToString(row[DocumentRevisionConstants.DRId.TrimAt()]);
                        documentRevisionData.Documentmanagerid = Convert.ToString(row[DocumentRevisionConstants.Documentmanagerid.TrimAt()]);
                        documentRevisionData.documenttitle = Convert.ToString(row[DocumentRevisionConstants.documenttitle.TrimAt()]);
                        documentRevisionData.documentno = Convert.ToString(row[DocumentRevisionConstants.documentno.TrimAt()]);
                        documentRevisionData.documenttype = Convert.ToString(row[DocumentRevisionConstants.documenttype.TrimAt()]);
                        documentRevisionData.department = Convert.ToString(row[DocumentRevisionConstants.department.TrimAt()]);
                        documentRevisionData.document = Convert.ToString(row[DocumentRevisionConstants.document.TrimAt()]);
                        documentRevisionData.EffectiveDate = DatatypeConverter.SetDateTime(row[DocumentRevisionConstants.EffectiveDate.TrimAt()]);
                        documentRevisionData.Reviewdate = DatatypeConverter.SetDateTime(row[DocumentRevisionConstants.Reviewdate.TrimAt()]);
                        documentRevisionData.CreatedBy = Convert.ToString(row[DocumentRevisionConstants.CreatedBy.TrimAt()]);
                        documentRevisionData.CreatedDate = DatatypeConverter.SetDateTime(row[DocumentRevisionConstants.CreatedDate.TrimAt()]);
                        documentRevisionData.ModifiedBy = Convert.ToString(row[DocumentRevisionConstants.ModifiedBy.TrimAt()]);
                        documentRevisionData.ModifiedDate = DatatypeConverter.SetDateTime(row[DocumentRevisionConstants.ModifiedDate.TrimAt()]);
                        result.Add(documentRevisionData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static DocumentRevision SetDocumentRevision(DataSet dataset)
        {
            var result = SetAllDocumentRevision(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
