//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    
    
    
    
    // Comment
    public interface IDocumentRevisionService
    {
        
        ResponseContext<DocumentRevision> GetAllDocumentRevision(RequestContext requestContext);
        
        DocumentRevision GetDocumentRevisionByDRId(string dRId);
        
        bool SaveDocumentRevision(DocumentRevision documentRevision);
        
        bool UpdateDocumentRevision(DocumentRevision documentRevision);
        
        bool DeleteDocumentRevisionByDRId(string dRId);
        
        bool DeleteAllDocumentRevision(List<int> dRIds);
    }
}
