//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    using VAMLIbrary.Core.Extentions;
    using Vlims.Entities;



    // Comment
    public static class DocumentTypeConfigurationConverter
    {
        
        public static List<DocumentTypeConfiguration> SetAllDocumentTypeConfiguration(DataSet dataset)
        {
            try
            {
                List<DocumentTypeConfiguration> result = new List<DocumentTypeConfiguration>();
                DocumentTypeConfiguration documentTypeConfigurationData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        documentTypeConfigurationData = new DocumentTypeConfiguration();
                        documentTypeConfigurationData.DTCId = Convert.ToString(row[DocumentTypeConfigurationConstants.DTCId.TrimAt()]);
                        documentTypeConfigurationData.DocumentMasterId = Convert.ToString(row[DocumentTypeConfigurationConstants.DocumentMasterId.TrimAt()]);
                        documentTypeConfigurationData.Documenttypename = Convert.ToString(row[DocumentTypeConfigurationConstants.Documenttypename.TrimAt()]);
                        documentTypeConfigurationData.documenttypeprefix = Convert.ToString(row[DocumentTypeConfigurationConstants.documenttypeprefix.TrimAt()]);
                        documentTypeConfigurationData.Description = Convert.ToString(row[DocumentTypeConfigurationConstants.Description.TrimAt()]);
                        documentTypeConfigurationData.Assigntodepartment = Convert.ToString(row[DocumentTypeConfigurationConstants.Assigntodepartment.TrimAt()]);
                        documentTypeConfigurationData.CreatedBy = Convert.ToString(row[DocumentTypeConfigurationConstants.CreatedBy.TrimAt()]);
                        documentTypeConfigurationData.CreatedDate = DatatypeConverter.SetDateTime(row[DocumentTypeConfigurationConstants.CreatedDate.TrimAt()]);
                        documentTypeConfigurationData.ModifiedBy = Convert.ToString(row[DocumentTypeConfigurationConstants.ModifiedBy.TrimAt()]);
                        documentTypeConfigurationData.ModifiedDate = DatatypeConverter.SetDateTime(row[DocumentTypeConfigurationConstants.ModifiedDate.TrimAt()]);
                        result.Add(documentTypeConfigurationData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static DocumentTypeConfiguration SetDocumentTypeConfiguration(DataSet dataset)
        {
            var result = SetAllDocumentTypeConfiguration(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
