//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using PolicySummary.Common.Entities;
    using PolicySummary.Sheet1.Entities;
    using PolicySummary.Sheet1.Data;
    
    
    // Comment
    public class DocumentTypeConfigurationService : IDocumentTypeConfigurationService
    {
        
        private readonly IDocumentTypeConfigurationData documentTypeConfigurationData;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="documentTypeConfigurationData"></param>
        public DocumentTypeConfigurationService(IDocumentTypeConfigurationData documentTypeConfigurationData)
        {
            this.documentTypeConfigurationData = documentTypeConfigurationData;
        }
        
        public ResponseContext<DocumentTypeConfiguration> GetAllDocumentTypeConfiguration(RequestContext requestContext)
        {
            try
            {
                DataSet dataset = documentTypeConfigurationData.GetAllDocumentTypeConfiguration(requestContext);
                List<DocumentTypeConfiguration> result = DocumentTypeConfigurationConverter.SetAllDocumentTypeConfiguration(dataset);
                return new ResponseContext<DocumentTypeConfiguration>() { RowCount = CommonConverter.SetRowsCount(dataset), Response = result };
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public DocumentTypeConfiguration GetDocumentTypeConfigurationByDTCId(int dTCId)
        {
            try
            {
                DataSet dataset = documentTypeConfigurationData.GetDocumentTypeConfigurationByDTCId(dTCId);
                DocumentTypeConfiguration result = DocumentTypeConfigurationConverter.SetDocumentTypeConfiguration(dataset);
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool SaveDocumentTypeConfiguration(DocumentTypeConfiguration documentTypeConfiguration)
        {
            try
            {
                String validationMessages = DocumentTypeConfigurationValidator.IsValidDocumentTypeConfiguration(documentTypeConfiguration);
                if (validationMessages.Length <= 0)
                {
                    var result = documentTypeConfigurationData.SaveDocumentTypeConfiguration(documentTypeConfiguration);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool UpdateDocumentTypeConfiguration(DocumentTypeConfiguration documentTypeConfiguration)
        {
            try
            {
                String validationMessages = DocumentTypeConfigurationValidator.IsValidDocumentTypeConfiguration(documentTypeConfiguration);
                if (validationMessages.Length <= 0)
                {
                    bool result = documentTypeConfigurationData.UpdateDocumentTypeConfiguration(documentTypeConfiguration);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteDocumentTypeConfigurationByDTCId(int dTCId)
        {
            try
            {
                return documentTypeConfigurationData.DeleteDocumentTypeConfigurationByDTCId(dTCId);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllDocumentTypeConfiguration(List<int> dTCIds)
        {
            try
            {
                return documentTypeConfigurationData.DeleteAllDocumentTypeConfiguration(dTCIds);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
