//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.DocumentMaster.DataAccess
{
    using System;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Vlims.Common;
    using Vlims.DocumentMaster.Entities;


    // Comment
    public static class workflowconigurationConverter
    {
        
        public static List<workflowconiguration> SetAllworkflowconiguration(DataSet dataset)
        {
            try
            {
                List<workflowconiguration> result = new List<workflowconiguration>();
                workflowconiguration workflowconigurationData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        workflowconigurationData = new workflowconiguration();
                        workflowconigurationData.WFCId = Convert.ToString(row[workflowconigurationConstants.WFCId.Trim()]);
                        workflowconigurationData.DocumentMasterId = Convert.ToString(row[workflowconigurationConstants.DocumentMasterId.Trim()]);
                        workflowconigurationData.documentstage = Convert.ToString(row[workflowconigurationConstants.documentstage.Trim()]);
                        workflowconigurationData.documenttype = Convert.ToString(row[workflowconigurationConstants.documenttype.Trim()]);
                        workflowconigurationData.department = Convert.ToString(row[workflowconigurationConstants.department.Trim()]);
                        workflowconigurationData.reviewsCount = DatatypeConverter.SetIntValue(row[workflowconigurationConstants.reviewsCount.Trim()]);
                        workflowconigurationData.approvalsCount = DatatypeConverter.SetIntValue(row[workflowconigurationConstants.approvalsCount.Trim()]);
                        workflowconigurationData.CreatedBy = Convert.ToString(row[workflowconigurationConstants.CreatedBy.Trim()]);
                        workflowconigurationData.CreatedDate = DatatypeConverter.SetDateTime(row[workflowconigurationConstants.CreatedDate.Trim()]);
                        workflowconigurationData.ModifiedBy = Convert.ToString(row[workflowconigurationConstants.ModifiedBy.Trim()]);
                        workflowconigurationData.ModifiedDate = DatatypeConverter.SetDateTime(row[workflowconigurationConstants.ModifiedDate.Trim()]);
                        result.Add(workflowconigurationData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static workflowconiguration Setworkflowconiguration(DataSet dataset)
        {
            var result = SetAllworkflowconiguration(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
