//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Administration.DataAccess
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Vlims.Administration.Entities;
    using Vlims.Common;


    // Comment
    public static class AdimManagementValidator
    {

        public static string IsValidAdimManagement(AdimManagement adimManagement)
        {
            try
            {
                StringBuilder validationMessages = new StringBuilder();
                ValidationHelper validationHelper = new ValidationHelper();
                validationMessages.Append(validationHelper.NullCheckValidator(adimManagement.AMId, nameof(adimManagement.AMId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(adimManagement.AMId, 150, nameof(adimManagement.AMId)));
                validationMessages.Append(validationHelper.LengthCheckValidator(adimManagement.SecurityManagement, 150, nameof(adimManagement.SecurityManagement)));
                validationMessages.Append(validationHelper.LengthCheckValidator(adimManagement.HierarchyManagement, 150, nameof(adimManagement.HierarchyManagement)));
                validationMessages.Append(validationHelper.LengthCheckValidator(adimManagement.PlantManagement, 150, nameof(adimManagement.PlantManagement)));
                validationMessages.Append(validationHelper.LengthCheckValidator(adimManagement.UserManagement, 150, nameof(adimManagement.UserManagement)));
                validationMessages.Append(validationHelper.LengthCheckValidator(adimManagement.CreatedBy, 150, nameof(adimManagement.CreatedBy)));
                validationMessages.Append(validationHelper.LengthCheckValidator(adimManagement.ModifiedBy, 150, nameof(adimManagement.ModifiedBy)));
                if (!String.IsNullOrEmpty(validationMessages.ToString()))
                {
                    return Convert.ToString(validationMessages.Remove(validationMessages.ToString().LastIndexOf(','), 1));
                }
                else
                {
                    return Convert.ToString(validationMessages);
                }
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
