//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Vlims.Entities.Common;
    using Vlims.Entities;



    // Comment
    public interface IUserConfigurationData
    {
        
        DataSet GetAllUserConfiguration(RequestContext requestContext);
        
        DataSet GetUserConfigurationByUCFId(string uCFId);
        
        bool SaveUserConfiguration(UserConfiguration userConfiguration);
        
        bool UpdateUserConfiguration(UserConfiguration userConfiguration);
        
        bool DeleteUserConfigurationByUCFId(string uCFId);
        
        bool DeleteAllUserConfiguration(List<int> uCFIds);
        
        DataSet GetUserConfigurationByUserManagementId(System.Int32? uMId);
        
        bool DeleteUserConfigurationByUserManagementId(System.Int32? uMId);
    }
}
