//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Entities
{
    using System;
    using System.Collections.Generic;
    
    
    public class DocumentMasterConstants
    {
        
        public const string Dmid = "@Dmid_PSY";
        
        public const string Documentypeconfiguration = "@Documentypeconfiguration_PSY";
        
        public const string Documentemplateonfiguration = "@Documentemplateonfiguration_PSY";
        
        public const string WorkFlowConfiguration = "@WorkFlowConfiguration_PSY";
        
        public const string NotificationConfiguration = "@NotificationConfiguration_PSY";
        
        public const string DashboardConfiguration = "@DashboardConfiguration_PSY";
        
        public const string CreatedBy = "@CreatedBy_PSY";
        
        public const string CreatedDate = "@CreatedDate_PSY";
        
        public const string ModifiedBy = "@ModifiedBy_PSY";
        
        public const string ModifiedDate = "@ModifiedDate_PSY";
        
        public const string USP_DocumentMaster_PSY_GET_ALL = "dbo.USP_DocumentMaster_PSY_GET_ALL";
        
        public const string USP_DocumentMaster_PSY_GET = "dbo.USP_DocumentMaster_PSY_GET";
        
        public const string USP_DocumentMaster_PSY_INSERT = "dbo.USP_DocumentMaster_PSY_INSERT";
        
        public const string USP_DocumentMaster_PSY_UPDATE = "dbo.USP_DocumentMaster_PSY_UPDATE";
        
        public const string USP_DocumentMaster_PSY_DELETE = "dbo.USP_DocumentMaster_PSY_DELETE";
        
        public const string USP_DocumentMaster_PSY_DELETE_ALL = "dbo.USP_DocumentMaster_PSY_DELETE_ALL";
        
        public const string USP_QuickDocumentMaster_INSERT = "dbo.USP_QuickDocumentMaster_INSERT";
        
        public const string USP_QuickDocumentMaster_UPDATE = "dbo.USP_QuickDocumentMaster_UPDATE";
    }
}
