//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using PolicySummary.Common.Entities;
    using PolicySummary.Sheet1.Entities;
    
    
    // Comment
    public interface IDocumentTemplateConfigurationData
    {
        
        DataSet GetAllDocumentTemplateConfiguration(RequestContext requestContext);
        
        DataSet GetDocumentTemplateConfigurationByDTID(int dTID);
        
        bool SaveDocumentTemplateConfiguration(DocumentTemplateConfiguration documentTemplateConfiguration);
        
        bool UpdateDocumentTemplateConfiguration(DocumentTemplateConfiguration documentTemplateConfiguration);
        
        bool DeleteDocumentTemplateConfigurationByDTID(int dTID);
        
        bool DeleteAllDocumentTemplateConfiguration(List<int> dTIDs);
    }
}
