//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using PolicySummary.Common.Entities;
    using PolicySummary.Sheet1.Entities;
    
    
    // Comment
    public interface IHierarchyManagementService
    {
        
        ResponseContext<HierarchyManagement> GetAllHierarchyManagement(RequestContext requestContext);
        
        HierarchyManagement GetHierarchyManagementByHMId(string hMId);
        
        bool SaveHierarchyManagement(HierarchyManagement hierarchyManagement);
        
        bool UpdateHierarchyManagement(HierarchyManagement hierarchyManagement);
        
        bool DeleteHierarchyManagementByHMId(string hMId);
        
        bool DeleteAllHierarchyManagement(List<int> hMIds);
    }
}
