//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    
    
    
    
    // Comment
    public interface IDocumentTemplateConfigurationService
    {
        
        ResponseContext<DocumentTemplateConfiguration> GetAllDocumentTemplateConfiguration(RequestContext requestContext);
        
        DocumentTemplateConfiguration GetDocumentTemplateConfigurationByDTID(int dTID);
        
        bool SaveDocumentTemplateConfiguration(DocumentTemplateConfiguration documentTemplateConfiguration);
        
        bool UpdateDocumentTemplateConfiguration(DocumentTemplateConfiguration documentTemplateConfiguration);
        
        bool DeleteDocumentTemplateConfigurationByDTID(int dTID);
        
        bool DeleteAllDocumentTemplateConfiguration(List<int> dTIDs);
    }
}
