//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    using VAMLIbrary.Core.Extentions;
    using Vlims.Entities;



    // Comment
    public static class DocumentEffectiveConverter
    {
        
        public static List<DocumentEffective> SetAllDocumentEffective(DataSet dataset)
        {
            try
            {
                List<DocumentEffective> result = new List<DocumentEffective>();
                DocumentEffective documentEffectiveData;
                if (dataset != null && dataset.Tables.Count > 0 && dataset.Tables[0].Rows.Count > 0)
                {
                    for (int i = 0; (i < dataset.Tables[0].Rows.Count); i = (i + 1))
                    {
                        DataRow row = dataset.Tables[0].Rows[i];
                        documentEffectiveData = new DocumentEffective();
                        documentEffectiveData.DEID = Convert.ToString(row[DocumentEffectiveConstants.DEID.TrimAt()]);
                        documentEffectiveData.Documentmanagerid = Convert.ToString(row[DocumentEffectiveConstants.Documentmanagerid.TrimAt()]);
                        documentEffectiveData.documenttitle = Convert.ToString(row[DocumentEffectiveConstants.documenttitle.TrimAt()]);
                        documentEffectiveData.documentno = Convert.ToString(row[DocumentEffectiveConstants.documentno.TrimAt()]);
                        documentEffectiveData.documenttype = Convert.ToString(row[DocumentEffectiveConstants.documenttype.TrimAt()]);
                        documentEffectiveData.department = Convert.ToString(row[DocumentEffectiveConstants.department.TrimAt()]);
                        documentEffectiveData.document = Convert.ToString(row[DocumentEffectiveConstants.document.TrimAt()]);
                        documentEffectiveData.EffectiveDate = DatatypeConverter.SetDateTime(row[DocumentEffectiveConstants.EffectiveDate.TrimAt()]);
                        documentEffectiveData.Reviewdate = DatatypeConverter.SetDateTime(row[DocumentEffectiveConstants.Reviewdate.TrimAt()]);
                        documentEffectiveData.CreatedBy = Convert.ToString(row[DocumentEffectiveConstants.CreatedBy.TrimAt()]);
                        documentEffectiveData.CreatedDate = DatatypeConverter.SetDateTime(row[DocumentEffectiveConstants.CreatedDate.TrimAt()]);
                        documentEffectiveData.ModifiedBy = Convert.ToString(row[DocumentEffectiveConstants.ModifiedBy.TrimAt()]);
                        documentEffectiveData.ModifiedDate = DatatypeConverter.SetDateTime(row[DocumentEffectiveConstants.ModifiedDate.TrimAt()]);
                        result.Add(documentEffectiveData);
                    }
                }
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public static DocumentEffective SetDocumentEffective(DataSet dataset)
        {
            var result = SetAllDocumentEffective(dataset);
            if (result.Count > 0)
            {
                return result.FirstOrDefault();
            }
            return null;
        }
    }
}
