//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Entities
{
    using System;
    using System.Collections.Generic;

    
    
    // Comment
    public class UserConfiguration
    {
        
        private string ucfidField;
        
        private string usermanagementidField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string useridField;
        
        private string departmentField;
        
        private string roleField;
        
        private string dojField;
        
        private System.Int32? empidField;
        
        private string emailidField;
        
        private string activedirectoryField;
        
        private string standarduserField;
        
        private string createdbyField;
        
        private DateTime? createddateField;
        
        private string modifiedbyField;
        
        private DateTime? modifieddateField;
        
        public string UCFId
        {
            get
            {
                return this.ucfidField;
            }
            set
            {
                this.ucfidField = value;
            }
        }
        
        public string UserManagementID
        {
            get
            {
                return this.usermanagementidField;
            }
            set
            {
                this.usermanagementidField = value;
            }
        }
        
        public string FirstName
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        public string LastName
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        public string UserID
        {
            get
            {
                return this.useridField;
            }
            set
            {
                this.useridField = value;
            }
        }
        
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        public string Doj
        {
            get
            {
                return this.dojField;
            }
            set
            {
                this.dojField = value;
            }
        }
        
        public System.Int32? Empid
        {
            get
            {
                return this.empidField;
            }
            set
            {
                this.empidField = value;
            }
        }
        
        public string EmailId
        {
            get
            {
                return this.emailidField;
            }
            set
            {
                this.emailidField = value;
            }
        }
        
        public string Activedirectory
        {
            get
            {
                return this.activedirectoryField;
            }
            set
            {
                this.activedirectoryField = value;
            }
        }
        
        public string Standarduser
        {
            get
            {
                return this.standarduserField;
            }
            set
            {
                this.standarduserField = value;
            }
        }
        
        public string CreatedBy
        {
            get
            {
                return this.createdbyField;
            }
            set
            {
                this.createdbyField = value;
            }
        }
        
        public DateTime? CreatedDate
        {
            get
            {
                return this.createddateField;
            }
            set
            {
                this.createddateField = value;
            }
        }
        
        public string ModifiedBy
        {
            get
            {
                return this.modifiedbyField;
            }
            set
            {
                this.modifiedbyField = value;
            }
        }
        
        public DateTime? ModifiedDate
        {
            get
            {
                return this.modifieddateField;
            }
            set
            {
                this.modifieddateField = value;
            }
        }
    }
}
