//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    using VAMLibrary.Core;
    using VAMLibrary.Core.Common;
    using Vlims.Entities.Common;
    using Vlims.Entities;


    // Comment
    public class AdditionalTaskData : IAdditionalTaskData
    {
        
        private readonly DataAccessHelper dataAccessHelper;
        
        public AdditionalTaskData(DataAccessHelper dataAccessHelper)
        {
            this.dataAccessHelper = dataAccessHelper;
        }
        
        public DataSet GetAllAdditionalTask(RequestContext requestContext)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = RequestContextConstants.PageNumber, Value = requestContext.PageNumber });
                sqlparms.Add(new SqlParameter { DbType = DbType.Int32, ParameterName = RequestContextConstants.PageSize, Value = requestContext.PageSize });
                DataSet dataset = (DataSet)dataAccessHelper.ExecuteStoredProcedure(AdditionalTaskConstants.USP_AdditionalTask_PSY_GET_ALL, sqlparms, ExecutionType.Dataset);
                return dataset;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public DataSet GetAdditionalTaskByATID(string aTID)
        {
            try
            {
                DataSet dataset = (DataSet)dataAccessHelper.ExecuteStoredProcedure(AdditionalTaskConstants.USP_AdditionalTask_PSY_GET, AdditionalTaskConstants.ATID, DbType.Int32, aTID, ExecutionType.Dataset);
                return dataset;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool SaveAdditionalTask(AdditionalTask additionalTask)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = AdditionalTaskConstants.Documentmanagerid, Value = additionalTask.Documentmanagerid });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = AdditionalTaskConstants.CreatedBy, Value = additionalTask.CreatedBy });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = AdditionalTaskConstants.ModifiedBy, Value = additionalTask.ModifiedBy });
                Object result = dataAccessHelper.ExecuteStoredProcedure(AdditionalTaskConstants.USP_AdditionalTask_PSY_INSERT, sqlparms, ExecutionType.Scalar);
                return (Convert.ToInt32(result) > 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool UpdateAdditionalTask(AdditionalTask additionalTask)
        {
            try
            {
                List<SqlParameter> sqlparms = new List<SqlParameter>();
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = AdditionalTaskConstants.ATID, Value = additionalTask.ATID });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = AdditionalTaskConstants.Documentmanagerid, Value = additionalTask.Documentmanagerid });
                sqlparms.Add(new SqlParameter { DbType = DbType.String, ParameterName = AdditionalTaskConstants.ModifiedBy, Value = additionalTask.ModifiedBy });
                Object result = dataAccessHelper.ExecuteStoredProcedure(AdditionalTaskConstants.USP_AdditionalTask_PSY_UPDATE, sqlparms, ExecutionType.Scalar);
                return (Convert.ToInt32(result) > 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAdditionalTaskByATID(string aTID)
        {
            try
            {
                var result = dataAccessHelper.ExecuteStoredProcedure(AdditionalTaskConstants.USP_AdditionalTask_PSY_DELETE, AdditionalTaskConstants.ATID, DbType.Int32, aTID, ExecutionType.NonQuery);
                return (Convert.ToInt32(result) >= 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllAdditionalTask(List<int> aTIDs)
        {
            try
            {
                var result = dataAccessHelper.ExecuteStoredProcedure(AdditionalTaskConstants.USP_AdditionalTask_PSY_DELETE_ALL, AdditionalTaskConstants.ATID, DbType.String, string.Join(',',  aTIDs), ExecutionType.NonQuery);
                return (Convert.ToInt32(result) >= 0);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
