//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolicySummary.Sheet1.Data
{
    using System;
    using System.Data;
    using System.Linq;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Vlims.Entities.Common;
    using Vlims.Entities;



    // Comment
    public interface IDocumentRevisionData
    {
        
        DataSet GetAllDocumentRevision(RequestContext requestContext);
        
        DataSet GetDocumentRevisionByDRId(string dRId);
        
        bool SaveDocumentRevision(DocumentRevision documentRevision);
        
        bool UpdateDocumentRevision(DocumentRevision documentRevision);
        
        bool DeleteDocumentRevisionByDRId(string dRId);
        
        bool DeleteAllDocumentRevision(List<int> dRIds);
    }
}
