//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    
    
    using PolicySummary.Sheet1.Data;
    using Vlims.Entities.Common;
    using Vlims.Entities;


    // Comment
    public class DocumentrequestService : IDocumentrequestService
    {
        
        private readonly IDocumentrequestData documentrequestData;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="documentrequestData"></param>
        public DocumentrequestService(IDocumentrequestData documentrequestData)
        {
            this.documentrequestData = documentrequestData;
        }
        
        public ResponseContext<Documentrequest> GetAllDocumentrequest(RequestContext requestContext)
        {
            try
            {
                DataSet dataset = documentrequestData.GetAllDocumentrequest(requestContext);
                List<Documentrequest> result = DocumentrequestConverter.SetAllDocumentrequest(dataset);
                return new ResponseContext<Documentrequest>() { RowCount = CommonConverter.SetRowsCount(dataset), Response = result };
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public Documentrequest GetDocumentrequestByDRID(string dRID)
        {
            try
            {
                DataSet dataset = documentrequestData.GetDocumentrequestByDRID(dRID);
                Documentrequest result = DocumentrequestConverter.SetDocumentrequest(dataset);
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool SaveDocumentrequest(Documentrequest documentrequest)
        {
            try
            {
                String validationMessages = DocumentrequestValidator.IsValidDocumentrequest(documentrequest);
                if (validationMessages.Length <= 0)
                {
                    var result = documentrequestData.SaveDocumentrequest(documentrequest);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool UpdateDocumentrequest(Documentrequest documentrequest)
        {
            try
            {
                String validationMessages = DocumentrequestValidator.IsValidDocumentrequest(documentrequest);
                if (validationMessages.Length <= 0)
                {
                    bool result = documentrequestData.UpdateDocumentrequest(documentrequest);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteDocumentrequestByDRID(string dRID)
        {
            try
            {
                return documentrequestData.DeleteDocumentrequestByDRID(dRID);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllDocumentrequest(List<int> dRIDs)
        {
            try
            {
                return documentrequestData.DeleteAllDocumentrequest(dRIDs);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
