//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    using Vlims.Entities.Common;
    using Vlims.Entities;




    // Comment
    public interface IDocumentrequestService
    {
        
        ResponseContext<Documentrequest> GetAllDocumentrequest(RequestContext requestContext);
        
        Documentrequest GetDocumentrequestByDRID(string dRID);
        
        bool SaveDocumentrequest(Documentrequest documentrequest);
        
        bool UpdateDocumentrequest(Documentrequest documentrequest);
        
        bool DeleteDocumentrequestByDRID(string dRID);
        
        bool DeleteAllDocumentrequest(List<int> dRIDs);
    }
}
