//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlims.Services
{
    using System;
    using System.Text;
    using System.IO;
    using System.Linq;
    using System.Data;
    using System.Collections.Generic;
    
    
    using PolicySummary.Sheet1.Data;
    using Vlims.Entities.Common;
    using Vlims.Entities;


    // Comment
    public class UserConfigurationService : IUserConfigurationService
    {
        
        private readonly IUserConfigurationData userConfigurationData;
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="userConfigurationData"></param>
        public UserConfigurationService(IUserConfigurationData userConfigurationData)
        {
            this.userConfigurationData = userConfigurationData;
        }
        
        public ResponseContext<UserConfiguration> GetAllUserConfiguration(RequestContext requestContext)
        {
            try
            {
                DataSet dataset = userConfigurationData.GetAllUserConfiguration(requestContext);
                List<UserConfiguration> result = UserConfigurationConverter.SetAllUserConfiguration(dataset);
                return new ResponseContext<UserConfiguration>() { RowCount = CommonConverter.SetRowsCount(dataset), Response = result };
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public UserConfiguration GetUserConfigurationByUCFId(string uCFId)
        {
            try
            {
                DataSet dataset = userConfigurationData.GetUserConfigurationByUCFId(uCFId);
                UserConfiguration result = UserConfigurationConverter.SetUserConfiguration(dataset);
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool SaveUserConfiguration(UserConfiguration userConfiguration)
        {
            try
            {
                String validationMessages = UserConfigurationValidator.IsValidUserConfiguration(userConfiguration);
                if (validationMessages.Length <= 0)
                {
                    var result = userConfigurationData.SaveUserConfiguration(userConfiguration);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool UpdateUserConfiguration(UserConfiguration userConfiguration)
        {
            try
            {
                String validationMessages = UserConfigurationValidator.IsValidUserConfiguration(userConfiguration);
                if (validationMessages.Length <= 0)
                {
                    bool result = userConfigurationData.UpdateUserConfiguration(userConfiguration);
                    return result;
                }
                throw new System.Exception(validationMessages);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteUserConfigurationByUCFId(string uCFId)
        {
            try
            {
                return userConfigurationData.DeleteUserConfigurationByUCFId(uCFId);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteAllUserConfiguration(List<int> uCFIds)
        {
            try
            {
                return userConfigurationData.DeleteAllUserConfiguration(uCFIds);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public List<UserConfiguration> GetUserConfigurationByUserManagementId(System.Int32? uMId)
        {
            try
            {
                DataSet dataset = userConfigurationData.GetUserConfigurationByUserManagementId(uMId);
                List<UserConfiguration> result = UserConfigurationConverter.SetAllUserConfiguration(dataset);
                return result;
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
        
        public bool DeleteUserConfigurationByUserManagementId(System.Int32? uMId)
        {
            try
            {
                return userConfigurationData.DeleteUserConfigurationByUserManagementId(uMId);
            }
            catch (System.Exception ex)
            {
                throw;
            }
        }
    }
}
